### ISSUE TITLE
Pagina personale utente

### ISSUE THREAD

**Issue by eutampieri** [eutampieri/sitoOII#44]
Come utente vorrei poter accedere alla mia pagina personale e vedere:

- [x] Dati sui problemi risolti #15 
- [x] Posizione nella classifica scolastica #15 
- [x] Eliminare il mio account #22 
- [ ] Scegliere come ricevere le comunicazioni #26 #28 #29 
- [ ] Modificare i dati utente
- [ ] Inserire e creare i badge utente #52
